# Generated by Django 5.1.4 on 2025-01-06 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_blogdetailmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogDetailModel',
        ),
    ]
