# Generated by Django 5.1.4 on 2025-01-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogcategorymodel_options_blogcommentmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcommentmodel',
            options={'verbose_name': 'blog comment', 'verbose_name_plural': 'blog comments'},
        ),
        migrations.AlterModelOptions(
            name='bloglikesmodel',
            options={'verbose_name': 'blog like', 'verbose_name_plural': 'blog likes'},
        ),
        migrations.AddField(
            model_name='blogcommentmodel',
            name='comment',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
