# Generated by Django 5.1.4 on 2025-01-05 18:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blogcommentmodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bloglikesmodel',
            unique_together={('blog', 'user')},
        ),
    ]
