# Generated by Django 5.1.4 on 2025-01-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_bloglikesmodel_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloglikesmodel',
            options={},
        ),
    ]
