# Generated by Django 5.1.4 on 2025-01-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_blogdetailmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailmodel',
            name='website',
            field=models.URLField(max_length=150),
        ),
    ]
