# Generated by Django 5.1.4 on 2025-01-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_blogdetailmodel_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailmodel',
            name='website',
            field=models.CharField(max_length=125),
        ),
    ]
