# Generated by Django 5.1.4 on 2025-01-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_alter_blogdetailmodel_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailmodel',
            name='website',
            field=models.EmailField(max_length=254),
        ),
    ]
