# Generated by Django 5.1.4 on 2024-12-31 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductModel',
        ),
    ]
