# Generated by Django 5.1.4 on 2024-12-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0004_delete_productmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='shop')),
                ('img1', models.ImageField(upload_to='shop')),
                ('img2', models.ImageField(upload_to='shop')),
                ('img3', models.ImageField(upload_to='shop')),
                ('img4', models.ImageField(upload_to='shop')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
